name: ⚓ Filter | Parse 🔰 
# This will likely increase as Repo Size gets bigger over time
#MAX_RUNTIME: 30-45 Mins
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  schedule:
    #- cron: "45 23 * * *" #( 11:45 PM UTC --> 05:30 AM Morning )
    - cron: "59 * * * *" #( Every 59 Mins )
#------------------------------------------------------------------------------------#
jobs:
  Parse:
    runs-on: ubuntu-latest
    #timeout-minutes: 45 # Can't afford to finish the 2000 Minutes quotes    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main  

      - name: Install Coreutils
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          sudo apt update -y
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
          # Again just because
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
        continue-on-error: true

      - name: Install eget
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          # eget for bins
          sudo wget "https://bin.ajam.dev/x86_64_Linux/eget" -O "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: false

      - name: Install Deps
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #anew
          sudo eget "https://bin.ajam.dev/x86_64_Linux/anew" --to "/usr/local/bin/anew"
          #asn
          sudo eget "https://bin.ajam.dev/x86_64_Linux/asn" --to "/usr/local/bin/asn"
          #asnmap
          sudo eget "https://bin.ajam.dev/x86_64_Linux/asnmap" --to "/usr/local/bin/asnmap"
          #cut-cdn
          sudo eget "https://bin.ajam.dev/x86_64_Linux/cut-cdn" --to "/usr/local/bin/cut-cdn"          
          # dirstat-rs for tree
          sudo eget "https://bin.ajam.dev/x86_64_Linux/ds" --to "/usr/local/bin/ds"          
          #dnsx
          sudo eget "https://bin.ajam.dev/x86_64_Linux/dnsx" --to "/usr/local/bin/dnsx"
          #HTTPx
          sudo eget "https://bin.ajam.dev/x86_64_Linux/httpx" --to "/usr/local/bin/httpx"
          #inscope
          sudo eget "https://bin.ajam.dev/x86_64_Linux/inscope" --to "/usr/local/bin/inscope"
          #mapcidr
          sudo eget "https://bin.ajam.dev/x86_64_Linux/mapcidr" --to "/usr/local/bin/mapcidr"
          #scopegen
          sudo eget "https://bin.ajam.dev/x86_64_Linux/scopegen" --to "/usr/local/bin/scopegen"
          #scopeview
          sudo eget "https://bin.ajam.dev/x86_64_Linux/scopeview" --to "/usr/local/bin/scopeview"
          #spk
          sudo eget "https://bin.ajam.dev/x86_64_Linux/spk" --to "/usr/local/bin/spk"
          #rclone
          sudo eget "https://bin.ajam.dev/x86_64_Linux/rclone" --to "/usr/local/bin/rclone"
          #yq
          sudo eget "https://bin.ajam.dev/x86_64_Linux/yq" --to "/usr/local/bin/yq"
        continue-on-error: true

      - name: Get Data
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #Latest --> 24 hr
          wget "https://pub.ajam.dev/datasets/certstream/all_latest.txt" -O "/tmp/certstream_domains.txt"
          echo -e "\n[+] Total Domains (certstream_domains_latest.txt): $(wc -l < /tmp/certstream_domains.txt)\n"
          echo -e "[+] Total Size (certstream_domains_latest.txt): $(du -h /tmp/certstream_domains.txt | awk '{print $1}')\n"
          #Weekly --> 7-8 Days
          wget "https://pub.ajam.dev/datasets/certstream/all_weekly.txt" -O "/tmp/certstream_domains_7days.txt"
          #Stats
          export SSL_7DAYS_TOTAL="$(wc -l < /tmp/certstream_domains_7days.txt)"
          echo "SSL_7DAYS_TOTAL=$SSL_7DAYS_TOTAL" >> $GITHUB_ENV
          echo -e "\n[+] Total Subs (certstream_domains_7days.txt): $SSL_7DAYS_TOTAL"
          echo -e "[+] Total Size (certstream_domains_7days.txt): $(du -h /tmp/certstream_domains_7days.txt | awk '{print $1}')\n"
        continue-on-error: true

      - name: Filter 🇧🇩 ccTLDs
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          mkdir -p "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs"
          cd "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs"
          # Source : https://bdia.btcl.com.bd/
          #(ALL)
          #Last 24 Hr
          #grep -Ei 'com\.bd|edu\.bd|gov\.bd|net\.bd|org\.bd|ac\.bd|mil\.bd|co\.bd|info\.bd' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_all_24h.txt"
          #.xn--54b7fta0cc --> .বাংলা
          grep -Ei '\.bd$|\.xn--54b7fta0cc$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_all_24h.txt"
          #Last 7 Days
          grep -Ei '\.bd$|\.xn--54b7fta0cc$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_all_7days.txt"
          #(Gov & Mil)
          #Last 24 Hr
          grep -Ei '\.gov\.bd$|\.mil\.bd$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_gov_mil_24h.txt"
          #Last 7 Days
          grep -Ei '\.gov\.bd$|\.mil\.bd$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_gov_mil_7days.txt"
          #(Edu)
          #Last 24 Hr
          grep -Ei '\.edu\.bd$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_edu_24h.txt"
          #Last 7 Days
          grep -Ei '\.edu\.bd$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_edu_7days.txt"
          #(ISP)
          #Last 24 Hr
          grep -E '\.accesstel\.net$|\.agni\.com$|\.bdcom\.com$|\.bol-online\.com$|\.bracnet\.net$|\.btcl\.gov\.bd$|\.dhakacom\.com$|\.earth\.net\.bd$|\.link3\.net$|\.mango\.com\.bd$|\.optimaxbd\.com$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_isp_24h.txt"
          #Last 7 Days
          grep -E '\.accesstel\.net$|\.agni\.com$|\.bdcom\.com$|\.bol-online\.com$|\.bracnet\.net$|\.btcl\.gov\.bd$|\.dhakacom\.com$|\.earth\.net\.bd$|\.link3\.net$|\.mango\.com\.bd$|\.optimaxbd\.com$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_isp_7days.txt"
        continue-on-error: true
        
      - name: Update README.md
        run: |
          # Presets
          set -x ; set +e
          #--------------#        
          cd "$GITHUB_WORKSPACE/main"
          #cat INFO
          #cat "$GITHUB_WORKSPACE/main/INFO.md" > "$GITHUB_WORKSPACE/main/README.md"
          echo -e "\n" > "$GITHUB_WORKSPACE/main/README.md"
          #Last 24 Hr
          echo '---' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "- #### 🖨️ **Stats** \`24Hr\`⏲️ ➼ $(date +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          #Total 
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < /tmp/certstream_domains.txt)\n" >> "$GITHUB_WORKSPACE/main/README.md"
          #bd_ccTLDs
          echo -e "\n--> 🇧🇩 bd_ccTLDs" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_all_24h.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (Edu): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_edu_24h.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (Gov|Mil): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_gov_mil_24h.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ISPs): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_isp_24h.txt)\n" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '---' >> "$GITHUB_WORKSPACE/main/README.md"
          #7Days
          echo -e "- #### 🖨️ **Stats** \`7Days\`⏲️ ➼ $(date +'%Y_%m_%d') <--> $(date -d "7 days ago" +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          #Total
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +${{ env.SSL_7DAYS_TOTAL }}\n" >> "$GITHUB_WORKSPACE/main/README.md"
          #bd_ccTLDs
          echo -e "\n--> 🇧🇩 bd_ccTLDs" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_all_7days.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (Edu): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_edu_7days.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (Gov|Mil): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_gov_mil_7days.txt)" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ISPs): +$(wc -l < $GITHUB_WORKSPACE/main/Data/bd_ccTLDs/certstream_domains_bd_isp_7days.txt)\n" >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          echo '---' >> "$GITHUB_WORKSPACE/main/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
          #cat INFO
          cat "$GITHUB_WORKSPACE/main/INFO.md" >> "$GITHUB_WORKSPACE/main/README.md"          
        continue-on-error: true
        
      - name: Get DateTime
        run: |
          # Date Time
          BANGLA_TIME=$(TZ='Asia/Dhaka' date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "BANGLA_TIME=$BANGLA_TIME" >> $GITHUB_ENV
          
      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: RebootEx # defaults to "github-actions[bot]"
          commit_user_email: Rebootex030@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "✅ ⚓ Filter | Parsed 🔰 CertStream Data 🌊 <-- ${{ env.BANGLA_TIME }} ⌚"
          #push_options: '--force'
